### ISSUE TITLE
How to accept a contact request ?

### ISSUE THREAD

**Issue by verybasicneeds** [Terrance/SkPy#109]
Hello,

I retrieve my pending contact requests with :

sk.contacts.requests()

But i didn't find how to accept a request ?

i tried :

sk.contacts["skypeuser"].accept()

and other things, but i can't find the good command.

Any hint?

Thank you by advance

**Comment by Terrance** [comment]
[`SkypeRequest.accept()`](https://skpy.t.allofti.me/api.html#skpy.user.SkypeRequest.accept)

You need to accept the request obtained from `sk.contacts.requests()`, not the user.

**Comment by verybasicneeds** [comment]
Thanks.

I tried :

sk.contacts.requests()
SkypeRequest.accept() 

I have several request pending and i get the error message :

**TypeError: unbound method accept() must be called with SkypeRequest instance as
first argument (got nothing instead)**

**Comment by Terrance** [comment]
That's an instance method, not a class method -- as stated above, call it on an instance of `SkypeRequest` rather than the class itself.

<sup>You may benefit from searching such errors online as this relates to basic Python rather than this library in particular -- please keep issues on-topic to bugs or questions with library usage.</sup>
