### ISSUE TITLE
saving/updating state?

### ISSUE THREAD

**Issue by cartertemm** [Terrance/SkPy#117]
I'm building an application with a small layer on top of Skpy. In this application, caching user data (contacts and conversations) is somewhat important and as I'd really rather not fetch everything on launch. I've looked through the code, docs and tracker and was unable to find anything of use.
What would be the best way of saving history to a file, loading at a later point, and updating entries in accordance with new events?

As a sidenote, I don't care about format. Object serialization or dumping into a database, whatever gets the job done. I tried pickling an entire conversation object but judging by the outrageous size of the result and integrated format of SkPy, I got far more than I bargained for.
Sorry if this doesn't exactly fit here, I looked but couldn't find a place for Q/A. I wouldn't mind implementing this if there's any interest whatsoever. Thanks for the project!

**Comment by Terrance** [comment]
If you're just listening for events via [`SkypeEventLoop`](https://skpy.t.allofti.me/api.html#skpy.main.SkypeEventLoop), you won't be pulling down user/chat info unless you access the corresponding attributes.  Given a [`SkypeMessageEvent`](https://skpy.t.allofti.me/api.html#skpy.event.SkypeMessageEvent), you can access `event.msg.userId` and `event.msg.chatId` without further API calls, in conjunction with your own local cache of users and chats (which can be fetched individually via dict key access of `Skype.contacts` and `Skype.chats`).

You'll likely want to check for any messages received whilst you were offline, in which case you'll need to iterate over [`SkypeChat.getMsgs()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.getMsgs) for each chat until you find one in your cache.

Pickling probably won't go well due to how the `Skype` object is passed around everywhere, which holds references to the user and chat caches.
