### ISSUE TITLE
How to check the expiry with sk.tokenExpiry?

### ISSUE THREAD

**Issue by JGhost-3** [Terrance/SkPy#131]

**Comment by Terrance** [comment]
See [`SkypeConnection.tokenExpiry`](https://skpy.t.allofti.me/internal.html#skpy.conn.SkypeConnection.tokenExpiry), or just look at it in a Python shell:

```python
>>> from skpy import Skype
>>> sk = Skype(...)
>>> sk.conn.tokenExpiry
{'skype': datetime.datetime(2020, 6, 27, 8, 0, 1),
 'reg': datetime.datetime(2020, 6, 27, 8, 0, 3)}
```

Typically you shouldn't need to read these, as your session will renew by itself on expiry, assuming you provided your password at startup rather than only a token file.
