### ISSUE TITLE
refreh token without username and password

### ISSUE THREAD

**Issue by sinanfarokm** [Terrance/SkPy#158]
Hi dear
with thanks to you, I am converting this useful library to java
and now, I need to refresh the token after expiration, would you please tell me how should I do about this?
I called the "`https://azwus1-client-s.gateway.messenger.live.com/v1/users/ME/endpoints`" and grabbed the `registrationToken` from its headers, but when I call APIs with this new token it returns 401 error and seems the token is not valid,
I need to know what should I do to have a fresh and valid new token.
thank you.

**Comment by Terrance** [comment]
All tokens invalidate after 24 hours, you need the user's credentials or their Microsoft account session to hand in order to request a new set of tokens.  Ideally you need a Microsoft login library for Java that can manage and persist that for you, though such libraries that automate the web login page don't really exist due to their fickle nature.
