### ISSUE TITLE
SkypeRefreshAuthProvider not works

### ISSUE THREAD

**Issue by farrokhpey** [Terrance/SkPy#159]
I tested SkypeRefreshAuthProvider multiple times but seems it doesn't work properly.
Could you please guide me on how to refresh the current token after expiration?

**Comment by Terrance** [comment]
The refresh provider is old and I think unlikely to work any more.  `SkypeConnection.refreshSkypeToken()` exists, but it's not used automatically -- if it doesn't just work then you're probably out of luck.  All tokens invalidate after 24 hours, you need the user's credentials or their Microsoft account session to hand in order to request a new set of tokens.
