### ISSUE TITLE
How to work with 2+ bots? 

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#194]
Hi! I created class
```
class SkypeBot:
    def __init__(self, username, password):
        self.username = username
        self.password = password
        self.session = Skype(self.username, self.password, tokenFile="skype_tokens")

a = SkypeBot("username1", "pass1")
b = SkypeBot("username2", "pass2")
```
And I found that 
`a.session` is on the same username as `b.session`

and in the same time this are correct as they must be:
```
a.username == "username1"
b.username == "username2"
```

To be much more clear I attach screen
![изображение](https://user-images.githubusercontent.com/30621622/170520582-a34b8f25-bd23-487f-9037-1d2e9d676844.png)

Without `tokenFile="skype_tokens"` and if I use method `def session` and not as attribute `self.session` it doesn't work too. 

So, how to work with 2+ different accounts? Are any ways? I think, that it is connected with your `SkypeConnection` object and `.conn` attribut, but I can't understand how to use it in my case.

**Comment by Terrance** [comment]
You're using the same token file for both instances, which means the first one authenticates and writes the token, and the second one reads the token and becomes the first user too (instead of authenticating as the second user).

As per #193, you should just leave `tokenFile` unset in order to have them both authenticate at startup.
