### ISSUE TITLE
Does `contacts.search` not find already added contacts?

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#200]
Hi! Is it ok behavior? I have empty list when `user_obj.contacts.search('contact_from_my_skype')`

**Comment by Terrance** [comment]
As a reminder, SkPy is merely a wrapper around the APIs that [Skype for Web](https://web.skype.com) consumes -- it applies no business logic of its own, and only a minimal amount of response parsing in order to produce well-structured results like `SkypeUser`.

Data problems like this are a consideration of the APIs, not of SkPy, and are out of scope here.  You should be able to produce the same result by using Skype for Web -- the issue template, which you keep clearing instead of filling in, requests that you do this before raising an issue.  Please take some time to familiarise yourself with Skype for Web and the features it makes available, and ensure your questions actually relate to this library rather than Skype or Python in general, which are out of scope here and better asked elsewere.
